### ISSUE TITLE
error on zat package

### ISSUE THREAD

**Issue by pedrorenan** [zendesk/zendesk_apps_tools#223]
Hi, when I try use zat package I receive this message

/Library/Ruby/Gems/2.3.0/gems/zendesk_apps_tools-2.8.1/lib/zendesk_apps_tools/command.rb:280:in `check_for_update': uninitialized constant ZendeskAppsTools::Command::DateTime (NameError)

**Comment by jbescoyez** [comment]
I have the same issue. @pedrorenan Have you found a workaround?

**Comment by PolRod** [comment]
Exact same error here for `zat validate`.

**Comment by pedrorenan** [comment]
Hi! 

I edited the file commenting the line that accused the error. I managed to use it quietly later.

**Comment by PolRod** [comment]
I added `require 'date'` to it and it worked as well (although I'm working now on an error occurring in zendesk_apps_support), but it would be nice to see it solved in the official release.

**Comment by nick-f** [comment]
@PolRod I've pinged the team responsible for Zendesk Apps Tools and they'll take a look at it when they can. Alternatively you can submit a PR if you have already made a fix and I'm sure that they'd appreciate that too :)

**Comment by svizzari** [comment]
@PolRod Your PR has now been merged and released in v2.8.4 of Zendesk Apps Tools.
