### ISSUE TITLE
zat theme preview doesn't work on ruby 2.6.*

### ISSUE THREAD

**Issue by gyndav** [zendesk/zendesk_apps_tools#276]
# Business rationale

While using `zat` to live preview a theme, I get a **422** if using **ruby** `2.6*`
However, `2.5.3` is fine.

# How to reproduce

While on **ruby 2.6***, run:
```
zat theme preview
```

I tried both with a valid password and an API token, both fails equally

**Comment by dbr2hb** [comment]
I can confirm this as well.  I believe zat server also will not work with 2.6. Ruby 2.5.3 works ok.

**Comment by gyndav** [comment]
I didn't dig, but upgrading to zat `3.2.4` with ruby `2.6.*` works now. Closing the issue then.
