### ISSUE TITLE
Install fails on MacOS Mojave 

### ISSUE THREAD

**Issue by alexfrench** [zendesk/zendesk_apps_tools#290]
I have just updated my MacOS to Mojave 10.14.4 and I'm finding that zendesk_apps_tools will no longer run. Have tried to re-install/update but get errors when doing so. 

partial error log here:

configure: error: in `/Users/alexfrench/.rvm/gems/ruby-2.6.0/gems/nokogiri-1.8.5/ext/nokogiri/tmp/x86_64-apple-darwin17.7.0/ports/libxml2/2.9.8/libxml2-2.9.8':
configure: error: C compiler cannot create executables.

I updated xcode command line tools. No change.

I drilled down a bit and I believe that the root of the problem may be the version of nokogirl (current version 10.3.1, version being installed by zendesk_apps_tools 1.8.5). 10.3.1 builds on Mojave. 1.8.5 does not (for me).

I'm not familiar with Ruby so would be great if someone could confirm this and offer a solution. Update to zendesk_apps_tools needed to support latest MacOS?

Thanks.

**Comment by hoangtrvu** [comment]
Hi @alexfrench, thanks for informing us of the issue. We've heard similar feedback about `zendesk_apps_tools` not working properly with Ruby 2.6.* and while this is something we'd like to patch in the long term, in the meantime can you try using Ruby 2.4.0 instead and see if it resolves the issue for you?

**Comment by alexfrench** [comment]
A belated answer to this. I managed to get things working again using Ruby 2.4.3. 

For those not familiar with the Ruby environment, this link was very helpful - I used RVM to set the version of Ruby. 

https://stackify.com/rvm-how-to-get-started-and-manage-your-ruby-installations
